CREATE TABLE IF NOT EXISTS web.user_account
(
  id SERIAL NOT NULL UNIQUE PRIMARY KEY COMMENT '自增ID',
  username VARCHAR(64) NOT NULL UNIQUE ,
  password VARCHAR(128) NOT NULL,
  salt VARCHAR(64) NOT NULL,
  realname VARCHAR(32),
  status  TINYINT(1) DEFAULT 0 COMMENT '账户状态：0-正常，1-锁定，2-注销'
) COMMENT '用户账号信息表';

CREATE TABLE IF NOT EXISTS web.role (
  id SERIAL NOT NULL UNIQUE PRIMARY KEY COMMENT '自增角色ID',
  name VARCHAR(32) NOT NULL ,
  department_id INTEGER COMMENT '角色所属部门'
) COMMENT '用户角色表';


CREATE TABLE IF NOT EXISTS web.department(
  id SERIAL NOT NULL UNIQUE PRIMARY KEY COMMENT '部门ID',
  name VARCHAR(32) NOT NULL
) COMMENT '部门表';

CREATE TABLE IF NOT EXISTS web.r_user_role(
  user_id INTEGER,
  role_id INTEGER
) COMMENT '用户角色表';

CREATE TABLE IF NOT EXISTS web.resource(
  id SERIAL NOT NULL UNIQUE PRIMARY KEY ,
  name VARCHAR(64),
  type VARCHAR(8) COMMENT '资源类型：MENU/BUTTON/API',
  code VARCHAR(32) COMMENT '资源编码',
  parent_id INTEGER ,
  uri VARCHAR(128),
  method VARCHAR(8),
  status VARCHAR(8) COMMENT '资源状态：NORMAL/FORBIDDEN',
  description VARCHAR(128)
) COMMENT '资源表';

